apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: forecasting-forecast-ms
  name: forecasting-forecast-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecasting-forecast-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forecasting-forecast-ms
    spec:
      containers:
      - image: forecasting-forecast-ms:latest
        name: forecasting-forecast-ms
        resources: {}
        env:
        - name: PORT
          value: "8000"
        - name: EVENT_SERVER
          value: "NATS"
        - name: MESSAGING_SERVER
          value: "NATS"
        - name: NATS_URL
          value: "nats://forecasting-nats-server:4222"
        imagePullPolicy: Never
status: {}
