apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: forecasting-forecast-access-ms
  name: forecasting-forecast-access-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecasting-forecast-access-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forecasting-forecast-access-ms
    spec:
      containers:
      - image: forecasting-forecast-access-ms
        name: forecasting-forecast-access-ms
        resources: {}
        env:
          - name: PORT
            value: "8000"
          - name: NATS_SERVERS
            value: "nats://forecasting-nats-server"
          - name: CACHE_SERVER
            value: "redis://forecasting-redis-cache:6379"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: forecasting-secrets
                key: DATABASE_URL_ACCESS
        imagePullPolicy: Never
status: {}
