apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: forecasting-redis-cache
  name: forecasting-redis-cache
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: forecasting-redis-cache
  type: ClusterIP
status:
  loadBalancer: {}
