apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: forecasting-client
  name: forecasting-client
spec:
  ports:
  - name: "5173"
    port: 5173
    protocol: TCP
    targetPort: 80
  selector:
    app: forecasting-client
  type: NodePort
status:
  loadBalancer: {}
